name: publish-to-github-pages
on:
  push:
    branches:
      - master
      - release/0.2.x

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest